const els={
  tabs:document.querySelector('#categoryTabs'),grid:document.querySelector('#mediaGrid'),template:document.querySelector('#cardTemplate'),
  search:document.querySelector('#searchInput'),sectionTitle:document.querySelector('#sectionTitle'),count:document.querySelector('#itemCount'),
  empty:document.querySelector('#emptyState'),error:document.querySelector('#errorState'),share:document.querySelector('#shareButton'),
  siteTitle:document.querySelector('#siteTitle'),siteSubtitle:document.querySelector('#siteSubtitle'),footer:document.querySelector('#footerText'),
  panel:document.querySelector('#playerPanel'),cover:document.querySelector('#playerCover'),playerTitle:document.querySelector('#playerTitle'),
  playerMeta:document.querySelector('#playerMeta'),audio:document.querySelector('#audioPlayer'),video:document.querySelector('#videoPlayer'),
  adminButton:document.querySelector('#adminButton'),adminPanel:document.querySelector('#adminPanel'),closeAdmin:document.querySelector('#closeAdminButton'),
  adminLoginBox:document.querySelector('#adminLoginBox'),adminLogin:document.querySelector('#adminLoginButton'),uploadForm:document.querySelector('#uploadForm'),
  uploadTitle:document.querySelector('#uploadTitle'),uploadSubtitle:document.querySelector('#uploadSubtitle'),uploadCategory:document.querySelector('#uploadCategory'),
  uploadDescription:document.querySelector('#uploadDescription'),uploadFile:document.querySelector('#uploadFile'),uploadSubmit:document.querySelector('#uploadSubmit'),
  uploadProgress:document.querySelector('#uploadProgress'),adminMessage:document.querySelector('#adminMessage')
};
const state={items:[],staticItems:[],remoteItems:[],category:'all',query:'',isAdmin:false};
const labels={all:'Wszystko',ai:'Muzyka AI',mine:'Moja muzyka',other:'Inna muzyka',music:'Muzyka',video:'Filmy',photo:'Zdjęcia',document:'Dokumenty',download:'Pliki'};
let auth=null,db=null,storage=null;

function txt(v,f=''){return typeof v==='string'&&v.trim()?v.trim():f}
function categoryKey(item){return item.category||item.type||'other'}
function categoryLabel(c){return labels[c]||c}
function rebuildItems(){state.items=[...state.staticItems,...state.remoteItems];renderTabs();renderItems()}
function renderTabs(){const cats=['all',...new Set(state.items.map(categoryKey).filter(Boolean))];els.tabs.replaceChildren();cats.forEach(cat=>{const b=document.createElement('button');b.className='tab'+(state.category===cat?' active':'');b.textContent=categoryLabel(cat);b.onclick=()=>{state.category=cat;renderTabs();renderItems()};els.tabs.appendChild(b)})}
function filtered(){return state.items.filter(i=>{const cat=state.category==='all'||categoryKey(i)===state.category;const hay=[i.title,i.subtitle,i.description,i.type,i.category].filter(Boolean).join(' ').toLocaleLowerCase('pl');return cat&&hay.includes(state.query)})}
function addButton(container,label,href,extraClass=''){const a=document.createElement('a');a.className='button '+extraClass;a.textContent=label;a.href=href;a.target='_blank';a.rel='noopener';container.appendChild(a)}
function renderItems(){const items=filtered();els.grid.replaceChildren();els.count.textContent=`${items.length} pozycji`;els.empty.hidden=items.length!==0;els.sectionTitle.textContent=categoryLabel(state.category);items.forEach(item=>{const n=els.template.content.cloneNode(true);n.querySelector('.card-cover').src=txt(item.cover,'./covers/default-cover.svg');n.querySelector('.card-cover').alt=`Okładka: ${txt(item.title,'materiał')}`;n.querySelector('.badge').textContent=categoryLabel(categoryKey(item));n.querySelector('.card-title').textContent=txt(item.title,'Bez tytułu');n.querySelector('.card-subtitle').textContent=txt(item.subtitle);const d=n.querySelector('.card-description');d.textContent=txt(item.description);d.hidden=!d.textContent;const actions=n.querySelector('.card-actions');const file=txt(item.file);if(item.type==='music'&&file){const b=document.createElement('button');b.className='button';b.textContent='▶ Odtwórz';b.onclick=()=>playMedia(item,'audio');actions.appendChild(b)}else if(item.type==='video'&&file){const b=document.createElement('button');b.className='button';b.textContent='▶ Odtwórz';b.onclick=()=>playMedia(item,'video');actions.appendChild(b)}else if(item.type==='photo'&&file){addButton(actions,'Otwórz zdjęcie',file)}else if(file){addButton(actions,'Otwórz',file)}if(file&&item.allowDownload!==false){const a=document.createElement('a');a.className='button ghost';a.textContent='Pobierz';a.href=file;a.download='';actions.appendChild(a)}els.grid.appendChild(n)})}
function playMedia(item,kind){els.panel.hidden=false;els.cover.src=txt(item.cover,'./covers/default-cover.svg');els.playerTitle.textContent=txt(item.title,'Bez tytułu');els.playerMeta.textContent=txt(item.subtitle);els.audio.pause();els.video.pause();els.audio.hidden=kind!=='audio';els.video.hidden=kind!=='video';const p=kind==='audio'?els.audio:els.video;p.src=item.file;p.play().catch(()=>{});els.panel.scrollIntoView({behavior:'smooth',block:'nearest'})}
function slugify(value){return txt(value,'utwor').toLocaleLowerCase('pl').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'utwor'}
function setAdminMessage(message,isError=false){els.adminMessage.textContent=message;els.adminMessage.classList.toggle('error',isError)}

async function loadRemoteItems(){if(!db)return;try{const snap=await db.collection('mediaItems').orderBy('createdAt','desc').get();state.remoteItems=snap.docs.map(d=>({id:d.id,...d.data()}));rebuildItems()}catch(e){console.warn('Nie udało się wczytać Firestore',e)}}
async function checkAdmin(user){state.isAdmin=false;els.uploadForm.hidden=true;els.adminLoginBox.hidden=!user;if(!user){setAdminMessage('');return}try{const [u,a]=await Promise.all([db.collection('users').doc(user.uid).get(),db.collection('admins').doc(user.uid).get()]);state.isAdmin=u.exists&&u.data().active===true&&a.exists&&a.data().role==='admin';els.adminLoginBox.hidden=state.isAdmin;els.uploadForm.hidden=!state.isAdmin;setAdminMessage(state.isAdmin?'Zalogowano jako administrator.':'To konto nie ma uprawnień administratora.',!state.isAdmin)}catch(e){setAdminMessage('Nie udało się sprawdzić uprawnień.',true)}}
async function loginAdmin(){if(!auth)return setAdminMessage('Firebase nie jest gotowy.',true);try{const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await auth.signInWithPopup(provider)}catch(e){setAdminMessage(`Logowanie nie powiodło się: ${e.message||e}`,true)}}
async function uploadTrack(event){event.preventDefault();if(!state.isAdmin)return setAdminMessage('Brak uprawnień administratora.',true);const file=els.uploadFile.files?.[0];if(!file)return setAdminMessage('Wybierz plik MP3.',true);if(file.size>100*1024*1024)return setAdminMessage('Plik jest większy niż 100 MB.',true);els.uploadSubmit.disabled=true;els.uploadProgress.hidden=false;els.uploadProgress.value=0;setAdminMessage('Przesyłanie pliku…');const category=els.uploadCategory.value;const filename=`${Date.now()}-${slugify(els.uploadTitle.value)}.mp3`;const ref=storage.ref().child(`media/music/${category}/${filename}`);const task=ref.put(file,{contentType:file.type||'audio/mpeg'});task.on('state_changed',s=>{els.uploadProgress.value=Math.round((s.bytesTransferred/s.totalBytes)*100)},e=>{els.uploadSubmit.disabled=false;setAdminMessage(`Błąd przesyłania: ${e.message||e}`,true)},async()=>{try{const url=await task.snapshot.ref.getDownloadURL();await db.collection('mediaItems').add({type:'music',category,title:txt(els.uploadTitle.value,'Bez tytułu'),subtitle:txt(els.uploadSubtitle.value,'Rumcajs'),description:txt(els.uploadDescription.value),file:url,cover:'./covers/default-cover.svg',allowDownload:false,createdAt:firebase.firestore.FieldValue.serverTimestamp(),ownerUid:auth.currentUser.uid});els.uploadForm.reset();els.uploadProgress.hidden=true;setAdminMessage('Utwór został dodany.');await loadRemoteItems()}catch(e){setAdminMessage(`Nie udało się zapisać utworu: ${e.message||e}`,true)}finally{els.uploadSubmit.disabled=false}})}

els.search.addEventListener('input',()=>{state.query=els.search.value.trim().toLocaleLowerCase('pl');renderItems()});
els.share.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);const t=els.share.textContent;els.share.textContent='Link skopiowany';setTimeout(()=>els.share.textContent=t,1500)}}catch(e){if(e.name!=='AbortError')console.error(e)}});
els.adminButton.addEventListener('click',()=>{els.adminPanel.hidden=false;els.adminPanel.scrollIntoView({behavior:'smooth',block:'start'})});
els.closeAdmin.addEventListener('click',()=>{els.adminPanel.hidden=true});
els.adminLogin.addEventListener('click',loginAdmin);
els.uploadForm.addEventListener('submit',uploadTrack);

async function init(){try{const r=await fetch('./media.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);const data=await r.json();const s=data.settings||{};els.siteTitle.textContent=txt(s.title,'Rumcajs Media Center');els.siteSubtitle.textContent=txt(s.subtitle,'Muzyka, filmy, zdjęcia i pliki w jednym miejscu');els.footer.textContent=txt(s.footer,'© 2026 Rumcajs Media Center');document.title=els.siteTitle.textContent;state.staticItems=Array.isArray(data.items)?data.items.filter(Boolean):[];rebuildItems()}catch(e){console.error(e);els.error.hidden=false}
  try{if(window.firebase&&firebase.apps.length){auth=firebase.auth();db=firebase.firestore();storage=firebase.storage();auth.onAuthStateChanged(checkAdmin);await loadRemoteItems()}else{setAdminMessage('Połączenie z Firebase nie jest jeszcze dostępne.',true)}}catch(e){console.error(e);setAdminMessage('Nie udało się uruchomić panelu administratora.',true)}
}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
init();
